title: Heavensbake Films
author: Tei Juan
email: tei-juan@hotmail.com
description: >-
  2023-2024
baseurl: ""
url: ""
google_analytics: G-9SSX7F4CJH

theme: minima
plugins:
  - jekyll-feed

collections_dir: collections
collections:
  posts:
    output: true
    permalink: /blog/:slug
  films:
    output: true
    permalink: /film/:slug
  names:
    output: true
    permalink: /name/:slug
    layout: name
  characters:
    output: true
    permalink: /bio/:slug

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "films"
    values:
      layout: "film"
  - scope:
      path: ""
      type: "names"
    values:
      layout: "name"
  - scope:
      path: ""
      type: "characters"
    values:
      layout: bio
      image: /assets/img/bio/:slug/:slug.jpg

signatureTei: João M. Teixeira, aka. Tei. Juan

show_excerpts: true