title: Heavensbake Studios
description: Thinking togravider
show_downloads: true
google_analytics: G-9SSX7F4CJH

plugins: [jekyll-feed, jekyll-seo-tag]

author:              'Tei Juan'
logo:                '/assets/images/logo.svg'

collections_dir: collections
collections:
  posts:
    output: true
    permalink: /:categories/:title
    layout: post
  films:
    output: true
    permalink: /film/:slug
    layout: film
  names:
    output: true
    permalink: /name/:slug
    layout: name
  characters:
    output: true
    permalink: /char/:slug
  novels:
    output: true
    permalink: /novel/:slug
    image: "/assets/icons/novels/:slug.jpg"
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "films"
    values:
      layout: "film"
  - scope:
      path: ""
      type: "names"
    values:
      layout: "name"
  - scope:
      path: ""
      type: "characters"
    values:
      layout: character
      image: "/assets/images/c/:slug/:slug.jpg"

signatureTei: João M. Teixeira, aka. Tei. Juan

show_excerpts: true
