title: Heavensbake Studios
description: Pregnancy and motherhood concepts
show_downloads: true
google_analytics: G-9SSX7F4CJH

collections_dir: collections
collections:
  films:
    output: true
    permalink: /film/:slug
    layout: film
  names:
    output: true
    permalink: /name/:slug
    layout: name
  characters:
    output: true
    permalink: /bio/:slug

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "films"
    values:
      layout: "film"
  - scope:
      path: ""
      type: "names"
    values:
      layout: "name"
  - scope:
      path: ""
      type: "characters"
    values:
      layout: bio
      image: /assets/images/bio/:slug/:slug.jpg

signatureTei: João M. Teixeira, aka. Tei. Juan

show_excerpts: true
