title: Heavensbake Films
author: Tei Juan
email: tei-juan@hotmail.com
description: >-
  Artists collaborating on anthro/human pregnancy films.
baseurl: ""
url: ""
twitter_username: heavensbake
google_analytics: G-9SSX7F4CJH

theme: minima
plugins:
  - jekyll-feed

collections_dir: collections
collections:
  films:
    output: true
    permalink: /film/:slug
  names:
    output: true
    permalink: /name/:slug
    layout: name

defaults:
  - scope:
      path: ""
      type: "films"
    values:
      layout: "film"
  - scope:
      path: ""
      type: "names"
    values:
      layout: "name"


signatureTei: João M. Teixeira, aka. Tei. Juan
