medias:
- { name: 'Films' , link: '/films' }
- { name: 'About Us' , link: '/about' }
- { name: 'Merch' , link: 'https://shop.heavensbake.com' }
- { name: 'Contact' , link: '/contact' }
- { name: 'Donate' , class: 'btn-donate', link: 'https://ko-fi.com/teijuan' }
