menu:
- {name: 'Clips', url: '/clips'}
- {name: 'Films', url: '/films'}
- {name: 'Advertising', url: '/advertising'}
- {name: 'Contact', url: 'https://teijuan.com/contact'}

social:
- {name: 'youtube', url: 'https://youtube.com/@heavensbake'}
- {name: 'envelope', url: 'mailto:contact@heavensbake.com'}
- {icon: 'rss-square', link: '/feed.xml'}

pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Share'

related_posts: 'You may also enjoy:'

bdgNew: '<sup><span style="text-shadow: 0px 0px 2px #ffaa00">**NEW!**</span></sup>'
